### ISSUE TITLE
Message service godoc refers to TCP

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro-testground#84]
https://github.com/statechannels/go-nitro-testground/blob/346d9a4ba169f26ccf37dcb30879995c81432672/messaging/service.go#L28

I think this is incorrect @lalexgap ? We use libp2p instead, I believe.

**Comment by geoknee** [comment]
Related question @lalexgap can you explain a bit about why there is a special messaging service in this repo? Why is it not in `go-nitro`? (Genuine Q)

**Comment by lalexgap** [comment]
> https://github.com/statechannels/go-nitro-testground/blob/346d9a4ba169f26ccf37dcb30879995c81432672/messaging/service.go#L28
> 
> I think this is incorrect @lalexgap ? We use libp2p instead, I believe.

We use  libp2p but we're using it over TCP/IP. Libp2p supports different [transports](https://docs.libp2p.io/concepts/transport/) so technically we could use another transport layer than TCP/IP.

I think this ends up meaning that `libp2p` functions fairly similar to our previous `tcp message service`. It just handles some of the complexities around addressing/throughput.

**Comment by lalexgap** [comment]
> Related question @lalexgap can you explain a bit about why there is a special messaging service in this repo? Why is it not in `go-nitro`? (Genuine Q)

I originally kept the message service in this repo because it was changing a lot based on the demands of the testground test. 

However at this point it is probably stable enough to be part of `go-nitro` proper. It would be good to replace the curretny tcp message service we have in go nitro, as it can crash under heavy load.

**Comment by lalexgap** [comment]
I think it makes sense to close this one. We could create create a seperate issue in the go nitro repo to port this service over.
