### ISSUE TITLE
Include some kind of version in dashboards

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro-testground#85]
It would be great to be able to correlate a test run with a certain set of changes.

**Comment by geoknee** [comment]
To solve this, we need some way of reading the version either in `go-nitro` or in `go-nitro-testground`.

**Comment by lalexgap** [comment]
As of `go 1.18` it looks like building a go executable will embed some versioning information: https://tip.golang.org/doc/go1.18#:~:text=mod%20download.)-,go%20version,-The%20go%20command
