### ISSUE TITLE
Highlight statechannels fork in README

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro-testground#91]
Is it worth highlighting that this is our fork?

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro-testground/pull/87#discussion_r973709785_

**Comment by kerzhner** [comment]
Close this issue once https://github.com/testground/testground/pull/1481 is merged in.

**Comment by geoknee** [comment]
@kerzhner should we update the readme to point to the official testground repo now (rather than our fork?)

**Comment by kerzhner** [comment]
Good point. Done in https://github.com/statechannels/go-nitro-testground/pull/131
